local ZoneConfig = {
	[1] = {
		Name = "Friche sale",
		PollutionThreshold = 0,
	},
	[2] = {
		Name = "Chantier industriel",
		PollutionThreshold = 1000,
	},
	[3] = {
		Name = "Charbon et vapeur",
		PollutionThreshold = 10000,
	},
	[4] = {
		Name = "Raffinerie toxique",
		PollutionThreshold = 100000,
	},
	[5] = {
		Name = "Apocalypse industrielle",
		PollutionThreshold = 1000000,
	},
}

return ZoneConfig
